name: phys_3340
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - jupyterlab>=3.0.0
  - numpy>=1.18.1
  - scipy>=1.3.0
  - notebook
  - matplotlib
  - pandas>=1.0.1
  - pandas-datareader
  - pip
  - jupytext 


